export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"Blog Home","icon":"home","type":"home","readingTime":{"minutes":0.54,"words":162},"excerpt":"This is a blog home page demo. To use this layout, you should set both layout: Blog and home: true in the page front matter. For related configuration docs, please see blog homepag"},["/index.html","/README.md"]],
  ["v-184f4da6","/intro.html",{"title":"关于博主","icon":"home","type":"home","readingTime":{"minutes":0.38,"words":115},"excerpt":"Intro Page 我是Ka Wai，中国香港人，就读国王伦敦学院还不确定什么专业的准大一生。 在香港、天津、和英国都生活过一段时间。 目前是计算机小白，还在学习中，发些帖子记录记录日常以及学习。如果有想交流学习的朋友可以加我微信哦"},["/intro","/intro.md"]],
  ["v-2d0ad528","/zh/",{"title":"博客主页","icon":"home","type":"home","readingTime":{"minutes":0.6,"words":179},"excerpt":""},["/zh/index.html","/zh/README.md"]],
  ["v-4eda55d8","/zh/posts/01.html",{"title":"02-初识数据类型 Notebook","icon":"blog","type":"article","readingTime":{"minutes":0.23,"words":68},"excerpt":"","author":"酒墨阿柴","date":"2022-04-30T12:10:52.000Z","localizedDate":"2022年4月30日","category":["编程笔记"],"tag":["Python","编程笔记"],"sticky":false,"star":false,"isOriginal":true},["/zh/posts/01","/zh/posts/01.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"Category","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"Tag","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"Articles","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"Encrypted","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"Slides","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"Star","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"Timeline","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-fbb94a6e","/zh/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/category/index.html"]],
  ["v-540234fd","/zh/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/tag/index.html"]],
  ["v-54d7ff21","/zh/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/article/index.html"]],
  ["v-1ad78213","/zh/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/encrypted/index.html"]],
  ["v-5b30cfc6","/zh/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/slide/index.html"]],
  ["v-2c3ee7f5","/zh/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/star/index.html"]],
  ["v-27b02be6","/zh/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/timeline/index.html"]],
  ["v-ad3309c6","/zh/category/%E7%BC%96%E7%A8%8B%E7%AC%94%E8%AE%B0/",{"title":"编程笔记 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/category/编程笔记/","/zh/category/%E7%BC%96%E7%A8%8B%E7%AC%94%E8%AE%B0/index.html"]],
  ["v-33a6e194","/zh/tag/python/",{"title":"Python 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/tag/python/index.html"]],
  ["v-686fb169","/zh/tag/%E7%BC%96%E7%A8%8B%E7%AC%94%E8%AE%B0/",{"title":"编程笔记 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/zh/tag/编程笔记/","/zh/tag/%E7%BC%96%E7%A8%8B%E7%AC%94%E8%AE%B0/index.html"]],
]
