export const data = JSON.parse("{\"key\":\"v-0bd3851d\",\"path\":\"/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/zh/column/pythonbasic.md/index.html.vue/index.html.js/index.html.vue/index.html.vue/index.html.js/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.js/index.html.vue/index.html.js/index.html.vue/index.html.js/index.html.js/\",\"title\":\"\",\"lang\":\"en-US\",\"frontmatter\":{\"summary\":\"export const data = JSON.parse(\\\"{\\\\\\\"key\\\\\\\":\\\\\\\"v-bd81c3fc\\\\\\\",\\\\\\\"path\\\\\\\":\\\\\\\"/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.v\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.imjmac.com/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/zh/column/pythonbasic.md/index.html.vue/index.html.js/index.html.vue/index.html.vue/index.html.js/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.js/index.html.vue/index.html.js/index.html.vue/index.html.js/index.html.js/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"J-MAC\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[],\"readingTime\":{\"minutes\":1.07,\"words\":320},\"filePathRelative\":\".vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/.vuepress/.temp/pages/zh/column/pythonbasic.md/index.html.vue/index.html.js/index.html.vue/index.html.vue/index.html.js/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.vue/index.html.js/index.html.vue/index.html.js/index.html.vue/index.html.js/index.html.js\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
